# Generated by Cyber Sandbox Creator
# https://gitlab.ics.muni.cz/muni-kypo-csc/cyber-sandbox-creator
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Device(router): router
  config.vm.define "router" do |device|
    device.vm.hostname = "router"
    device.vm.box = "munikypo/debian-10"
    device.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end
    device.vm.network "private_network",
      virtualbox__intnet: "switch",
      ip: "10.1.26.1",
      netmask: "255.255.255.0"
  end

  # Device(host): attacker
  config.vm.define "attacker" do |device|
    device.vm.hostname = "attacker"
    device.vm.box = "munikypo/kali-2020.4"
    device.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end
    device.vm.network "private_network",
      virtualbox__intnet: "switch",
      ip: "10.1.26.23",
      netmask: "255.255.255.0"
  end

  # Device(host): server
  config.vm.define "server" do |device|
    device.vm.hostname = "server"
    device.vm.box = "munikypo/debian-10"
    device.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end
    device.vm.network "private_network",
      virtualbox__intnet: "switch",
      ip: "10.1.26.9",
      netmask: "255.255.255.0"
  end

  # Device(host): client
  config.vm.define "client" do |device|
    device.vm.hostname = "client"
    device.vm.box = "munikypo/debian-10"
    device.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end
    device.vm.network "private_network",
      virtualbox__intnet: "switch",
      ip: "10.1.26.4",
      netmask: "255.255.255.0"
  end

  # Ansible pre-configuration
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "preconfig/playbook.yml"
    ansible.inventory_path = "preconfig/hosts.yml"
  end

  # User Ansible provisioning
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    provisioner.raw_arguments = Shellwords.shellsplit(ENV['ANSIBLE_ARGS']) if ENV['ANSIBLE_ARGS']
    ansible.galaxy_role_file = "provisioning/requirements.yml"
    ansible.galaxy_roles_path = "provisioning/roles"
    ansible.galaxy_command = "sudo ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path} --force"
  end
end
