- name: sandbox-logging-bash
  src: git@gitlab.ics.muni.cz:muni-kypo/ansible-roles/sandbox-logging-bash.git
  scm: git
  version: 1.0.0

- name: sandbox-logging-msf
  src: git@gitlab.ics.muni.cz:muni-kypo/ansible-roles/sandbox-logging-msf.git
  scm: git
  version: 1.0.0

- name: sandbox-logging-forward
  src: git@gitlab.ics.muni.cz:muni-kypo/ansible-roles/sandbox-logging-forward.git
  scm: git
  version: 1.0.0
