---
all:
  children:
    hosts:
      hosts:
        attacker: {}
        client: {}
        server: {}
    routers:
      hosts:
        router: {}
    ssh:
      hosts:
        attacker: {}
        client: {}
        router: {}
        server: {}
    winrm:
      hosts: {}
  hosts:
    attacker: {}
    client: {}
    router: {}
    server: {}
...
